# Generated by Django 4.2.3 on 2023-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=500)),
                ("price", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("date_added", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
